name: Build and push images

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Budowa i wypchniecie obrazu
    runs-on: ubuntu-20.04
    steps:
      - name: Sprawdzenie kodu
        uses: actions/checkout@v3

      - name: Ustawienie QEMU
        uses: docker/setup-qemu-action@v2

      - name: Incijalizacja Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/pawelwojcik7/Fibonacci
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Logowanie do Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Logowanie do GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,mode=max,ref=353362/fibcalc:cache
          cache-to: type=registry,mode=max,ref=353362/fibcalc:cache
          context: FibCalc
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
